In [1]:
import wrds
db = wrds.Connection()

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

In [ ]:
# [x for x in db.list_libraries() if 'option' in x]
# [x for x in db.list_tables(library='optionm') if 'option' in x]

# db.describe_table(library='optionm', table='security_price')
# db.describe_table(library='optionm', table='option_history')

In [2]:
import pandas as pd

riy_consti = pd.read_excel('RIY Index Constituents.xlsx')
riy_consti.columns = pd.to_datetime(riy_consti.columns, format='%Y%m%d')
riy_consti

,2000-09-01,2001-09-01,2002-09-01,2003-09-01,2004-09-01,2005-09-01,2006-09-01,2007-09-01,2008-09-01,2009-09-01,...,2015-09-01,2016-09-01,2017-09-01,2018-09-01,2019-09-01,2020-09-01,2021-09-01,2022-09-01,2023-09-01,2024-09-01
0,A UN,A UN,A UN,A UN,A UN,A UN,A UN,A UN,A UN,A UN,...,A UN,A UN,A UN,A UN,A UN,A UN,A UN,A UN,A UN,A UN
1,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,...,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN,AA UN
2,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,...,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW,AAL UW
3,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,...,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW,AAON UW
4,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,...,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN,AAP UN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,...,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW,ZI UW
1005,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,...,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW,ZION UW
1006,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,...,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW,ZM UW
1007,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,...,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW,ZS UW
1008,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,...,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN,ZTS UN

In [13]:
db.raw_sql(
    """
    select *
    from optionm_all.opprcd2023 a, optionm.securd b
    where a.secid = b.secid
    and b.ticker = 'PCVX'

""")

,secid,date,symbol,symbol_flag,exdate,last_date,cp_flag,strike_price,best_bid,best_offer,...,suffix,secid,cusip,ticker,sic,index_flag,exchange_d,class,issue_type,industry_group
0,214350.0,2023-01-20,PCVX 230120C25000,1,2023-01-20,2023-01-11,C,25000.0,18.40,22.5,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
1,214350.0,2023-01-20,PCVX 230120C30000,1,2023-01-20,2022-10-21,C,30000.0,13.60,17.5,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
2,214350.0,2023-01-20,PCVX 230120C35000,1,2023-01-20,2023-01-20,C,35000.0,9.20,12.5,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
3,214350.0,2023-01-20,PCVX 230120C40000,1,2023-01-20,2023-01-20,C,40000.0,4.40,7.5,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
4,214350.0,2023-01-20,PCVX 230120C45000,1,2023-01-20,2023-01-20,C,45000.0,0.05,4.5,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15823,214350.0,2023-08-31,PCVX 240419P50000,1,2024-04-19,None,P,50000.0,3.20,6.8,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
15824,214350.0,2023-08-31,PCVX 240419P55000,1,2024-04-19,None,P,55000.0,6.90,9.3,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
15825,214350.0,2023-08-31,PCVX 240419P60000,1,2024-04-19,None,P,60000.0,10.20,12.3,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
15826,214350.0,2023-08-31,PCVX 240419P65000,1,2024-04-19,None,P,65000.0,12.60,16.3,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None
15827,214350.0,2023-08-31,PCVX 240419P70000,1,2024-04-19,None,P,70000.0,17.70,20.0,...,None,214350.0,92243G10,PCVX,2836,0,4.0,None,0,None

In [20]:
import pandas as pd
import yfinance as yf

russell_ticker = pd.read_excel('rusellticker.xlsx')
russell_ticker_list = [str(x) for x in russell_ticker['ticker'] if x == x]
data = yf.download(russell_ticker_list, start='2023-01-01')
data.index = pd.to_datetime(data.index)
data = data.swaplevel(0, 1, axis=1).sort_index(axis=1)
data

[*******               14%%                      ]  287 of 1998 completed

Failed to get ticker 'CRD/A' reason: Expecting value: line 1 column 1 (char 0)

[***************       31%%                      ]  617 of 1998 completed

Failed to get ticker 'LGF/A' reason: Expecting value: line 1 column 1 (char 0)

[**********************49%%                      ]  987 of 1998 completed

Failed to get ticker 'MOG/A' reason: Expecting value: line 1 column 1 (char 0)

[**********************56%%*                     ]  1112 of 1998 completed

Failed to get ticker 'GEF/B' reason: Expecting value: line 1 column 1 (char 0)

[**********************78%%***********           ]  1561 of 1998 completed

Failed to get ticker 'LGF/B' reason: Expecting value: line 1 column 1 (char 0)

[*********************100%%**********************]  1998 of 1998 completed

19 Failed downloads:
['DDRN', 'CRD/A', 'SNPO', 'CATC', 'LGF/A', 'DCPH', 'MOG/A', 'GEF/B', 'HRT', 'NYCBN', 'WIRE', 'LGF/B', 'ETRN', 'CVLY', 'TARO', 'NWLI']: Exception('%ticker%: No timezone found, symbol may be delisted')
['MODN', 'EVBG']: Exception('%ticker%: No data found, symbol may be delisted')
['DNMRW']: Exception("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")

                 AAN                                            AAOI         \
           Adj Close  Close   High     Low   Open   Volume Adj Close  Close
Date
2023-01-03     11.85  11.85  12.36  11.800  12.16   343000      1.88   1.88
2023-01-04     12.70  12.70  12.71  11.930  12.06   335000      1.92   1.92
2023-01-05     12.75  12.75  12.77  12.330  12.58   211200      1.88   1.88
2023-01-06     13.05  13.05  13.11  12.670  12.85   237400      1.86   1.86
2023-01-09     13.28  13.28  13.42  13.000  13.12   320200      2.15   2.15
...              ...    ...    ...     ...    ...      ...       ...    ...
2024-09-16     10.06  10.06  10.06  10.045  10.06   573800     13.19  13.19
2024-09-17     10.06  10.06  10.06  10.040  10.05   801500     13.58  13.58
2024-09-18     10.05  10.05  10.06  10.045  10.06   477800     13.28  13.28
2024-09-19     10.04  10.04  10.07  10.030  10.07  1054200     14.20  14.20
2024-09-20     10.02  10.02  10.04  10.020  10.03  1571983     13.83  13.83

                            ...    ZYME                              ZYXI  \
              High     Low  ...    High     Low   Open   Volume Adj Close
Date                        ...
2023-01-03   1.990   1.860  ...   8.210   7.450   7.95   716000     13.88
2023-01-04   1.950   1.880  ...   7.820   7.500   7.63   356100     14.11
2023-01-05   1.920   1.870  ...   8.195   7.410   7.44  1022700     14.14
2023-01-06   1.909   1.830  ...   8.000   7.540   8.00   673900     15.65
2023-01-09   2.280   1.923  ...   7.815   7.500   7.67   567800     15.65
...            ...     ...  ...     ...     ...    ...      ...       ...
2024-09-16  14.710  13.160  ...  12.690  12.400  12.60   676900      7.97
2024-09-17  13.670  13.179  ...  12.660  12.089  12.50  1049200      8.19
2024-09-18  13.890  12.800  ...  12.780  12.245  12.30   631800      8.18
2024-09-19  14.390  13.640  ...  13.140  12.550  12.72   717100      8.33
2024-09-20  14.150  13.550  ...  13.230  12.890  13.04   660593      8.12


            Close   High    Low   Open   Volume
Date
2023-01-03  13.88  14.48  13.85  14.17   182600
2023-01-04  14.11  14.24  13.86  13.91    99800
2023-01-05  14.14  14.26  13.96  14.15   122800
2023-01-06  15.65  17.25  14.53  14.55  1142500
2023-01-09  15.65  16.10  15.10  15.79   333600
...           ...    ...    ...    ...      ...
2024-09-16   7.97   8.21   7.74   8.20   144200
2024-09-17   8.19   8.45   7.99   8.10   120400
2024-09-18   8.18   8.44   8.10   8.27    97700
2024-09-19   8.33   8.59   8.27   8.29   142700
2024-09-20   8.12   8.47   8.12   8.35   271262

[432 rows x 11988 columns]

In [46]:
col =data.columns[data.isna().any()].tolist()
col_names = []
for c in col:
    if c[0] not in col_names:
        col_names.append(str(c[0]))
    else:
        continue
col_names

['AESI',
 'AHR',
 'ALIM',
 'AMK',
 'ANRO',
 'APGE',
 'ATMU',
 'ATRI',
 'AVBP',
 'BOLD',
 'BTSG',
 'CATC',
 'CERE',
 'CGON',
 'CORZ',
 'CRD/A',
 'CRGX',
 'CRVO',
 'CTNM',
 'CTRI',
 'CVLY',
 'DBD',
 'DCPH',
 'DDRN',
 'DEC',
 'DNMRW',
 'DO',
 'ELVN',
 'ETRN',
 'EVBG',
 'FBLG',
 'FIHL',
 'FREE',
 'GEF/B',
 'GTHX',
 'GUTS',
 'HA',
 'HG',
 'HIBB',
 'HRT',
 'HSHP',
 'IBTA',
 'INBX',
 'ISPR',
 'KGS',
 'KLG',
 'KNF',
 'KYTX',
 'LGF/A',
 'LGF/B',
 'LXEO',
 'MCBC',
 'METCB',
 'MGX',
 'MLYS',
 'MODN',
 'MOG/A',
 'MORF',
 'MSGE',
 'NATL',
 'NBBK',
 'NLOP',
 'NMRA',
 'NWLI',
 'NXT',
 'NYCBN',
 'PACS',
 'PHIN',
 'PKST',
 'RENB',
 'SEZL',
 'SKWD',
 'SLRN',
 'SMXT',
 'SNPO',
 'STHO',
 'STRW',
 'SUNS',
 'SVV',
 'TARO',
 'TELO',
 'VTS',
 'WIRE',
 'WS',
 'ZURA']